apiVersion: apps/v1
kind: Deployment
metadata:
  name: -deployment
  labels:
    app: 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 

    spec:
      containers:
        - name: 
          image: 
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: -config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: -config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: -secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: -db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: ""

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: -secrets
                  key: mysql-root-password