kind: Service
apiVersion: v1
metadata:
  name: account-service1
spec:
  selector:
    app: myapp2
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port of application
      targetPort: 3000
      # Port accessible outside cluster
      nodePort: 30003
  type: LoadBalancer
 
 
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  replicas: 5
   selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: account
          image: widjesh/account-service:lts
          ports:
            - containerPort: 8080