apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service

    spec:
      containers:
        - name: account-service
          image: widjesh/account-service:account-service
          ports:
            - containerPort: 3000
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: account-service-db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "3000"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: mysql-root-password
