apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service

    spec:
      containers:
        - name: account-service
          image: widjesh/account-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: service-api-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: jwt-secret
           
