POST http://localhost:3000/register
Content-Type: application/json

{
    "firstname":"Shiva",
    "lastname":"bhaggan",
    "email":"wsbhaggan@mum.edu",
    "password":"test",
    "address":"1000 N 4th Street",
    "payment":"Paypal"
}

###
GET http://localhost:3000/
###
GET http://localhost:3000/find/wsbhaggan@mum.edu
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"wsbhaggan@mum.edu",
    "password":"test"
}

###
GET http://192.168.64.7:31281/

###
POST http://192.168.64.7:30029/register
Content-Type: application/json

{
    "firstname":"Shiva",
    "lastname":"bhaggan",
    "email":"wsbhaggan@mum.edu",
    "password":"test",
    "address":"1000 N 4th Street",
    "payment":"Paypal"
}

###
POST http://192.168.64.7:30029/login
Content-Type: application/json

{
    "email":"wsbhaggan@mum.edu",
    "password":"test"
}
